spring:
  profiles:
    active: test

management:
  endpoints:
    enabled-by-default: false
#    enabled-by-default: true
    web:
      exposure:
        include: health,info,loggers,shutdown,prometheus
#        include: health,info,loggers
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
    info:
      enabled: true
    loggers:
      enabled: true
    shutdown:
      enabled: true
    prometheus:
      enabled: true
